version: '3.8'

services:
    db:
        image: aixmazone/mysql
        build:
          context: mysql
          args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        volumes:
            - ./mysql/database:/var/lib/mysql
        restart: always
        #user: mysql # uncomment on subsequent starts
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: aixmazone/wordpress
        build:
          context: wordpress
          args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        depends_on:
            - db
        ports:
            - 8080:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./wordpress/aixmazone.ini:/usr/local/etc/php/conf.d/aixmazone.ini:ro
            - ./wordpress/src:/var/www/html
